### ISSUE TITLE
Level 3 slides title

### ISSUE THREAD

**Issue by tchevri** [shafayetShafee/metropolis#2]
Since I have your attention, can I ask you a newbie question en passant please? Your template works great, especially with level 2 slides, but when i change to level 3 slides (`slide-level: 3` in the `yml` section), I do not feel like I am getting the same nice layout anymore, in particular slide heading fonts are not differentiated and even turn into small text... Does it mean i need to go mess with the .csss file or is there another easier solution? sorry for bothering you with this pedestrian question. much appreciated your help.

as a MWE, in your temple, just simply add an extra # to all your slides to make them level 3, so instead of `## slide title`, you will have `### slide title` (so specifically, in the previous issues' screenshots, just write `### quarto` insead of `## quarto`). Then in your `yml` you specify: `slide-level: 3`. Render and see for yourself how the font is just regular. hence my question. Sorry for troubling you.

**Comment by shafayetShafee** [comment]
Okay, yes I can reproduce the problem. This is happening because the styles for the headers are hard coded, so they are not working as intended when slide level 3 is used.

https://github.com/shafayetShafee/metropolis/blob/801d84f79093f008063122b853759247c4d711d3/_extensions/metropolis/metropolis.scss#L65-L95


However, a quick solution might be the following,


**style.css**

``` css
.reveal h3 {
  font-size: var(--r-heading3-size);
}
```

~~~
---
title: "Metropolis-Revealjs"
format:
  metropolis-revealjs: default
slide-level: 3
css: style.css
---

### Hello, There

This presentation will show you examples of what you can do with Quarto and [Reveal.js](https://revealjs.com), including:

-   Presenting code and LaTeX equations
-   Including computations in slide output
-   Image, video, and iframe backgrounds
-   Fancy transitions and animations
-   Printing to PDF

...and much more

### Pretty Code {auto-animate="true"}

-   Over 20 syntax highlighting themes available
-   Default theme optimized for accessibility

``` r
# Define a server for the Shiny app
function(input, output) {
  
  # Fill in the spot we created for a plot
  output$phonePlot <- renderPlot({
    # Render a barplot
  })
}
```

::: footer
Learn more: [Syntax Highlighting](https://quarto.org/docs/output-formats/html-code.html#highlighting)
:::

~~~

**Comment by tchevri** [comment]
Thank you so much!
